### ISSUE TITLE
I cannot connect to the custom region

### ISSUE THREAD

**Issue by Francis47RojoEFE** [Woodi-dev/Among-Us-Sheriff-Mod#101]
I cannot find games, enter codes, neither create games.. it works if i select North America but custom dosent. I downloaded the files on the gifthub and dragged them into my among us pressed amongus.exe and it all works fine but the custom thing
![image](https://user-images.githubusercontent.com/79424950/108640880-916f0d00-7472-11eb-8be8-8bd9d651b23d.png)

**Comment by Woodi-dev** [comment]
Yes it works like intended. The custom server connects to your local pc (default).
You have to configure it first in the config file. (Specify Ip address of a custom server).
You don't need to connect to the Custom Server Region. You can play the mod on public servers.
I have added this option in the case the devs do not allow to play on their servers anymore.
