### ISSUE TITLE
How do you download it ?

### ISSUE THREAD

**Issue by alison-2252** [Woodi-dev/Among-Us-Sheriff-Mod#102]
How do u download it it's not clear

**Comment by florianbelhomme** [comment]
https://github.com/Woodi-dev/Among-Us-Sheriff-Mod/releases/download/v1.1/Among.Us.Sheriff.Mod.1.1.zip

**Comment by Woodi-dev** [comment]
https://www.youtube.com/watch?v=8_lF9AHyULw&t=49s
