### ISSUE TITLE
Screen stays black 

### ISSUE THREAD

**Issue by autumn1438** [Woodi-dev/Among-Us-Sheriff-Mod#110]
When I open the file the main screen loads and I get into a lobby but then when it’s time to play the game the screen stays black and I can’t see anything. I noticed that I’m missing the icon.ico file is that an issue?

**Comment by Woodi-dev** [comment]
Make sure Lobby Leader and other players have installed the mod.
Otherwise, feel free to paste the content of BepInEx/logOutput.txt here

**Comment by autumn1438** [comment]
yes everyone has the sheriff mod and this is the BeplnEx/logOutput.txt looks like

[Message: Preloader] BepInEx 6.0.0-reactor.16 - Among Us
[Message: Preloader] BLEEDING EDGE Build #16 from a44ed820546a57f00af344eb86ba879e270b71d3 at reactor
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2019.4.9.5308042
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Sheriff Mod 1.2.0]
[Message:Sheriff Mod] Sheriff Mod loaded
[Message:   BepInEx] Chainloader startup complete
[Error  :    Detour] System.NullReferenceException: Object reference not set to an instance of an object
  at SheriffMod.IntroCutScenePatch.Postfix (IntroCutscene+OIBLPHFGCPC __instance) [0x00006] in <db094fd37572425fa4831a1c5358b071>:0 
  at (wrapper dynamic-method) IntroCutscene+OIBLPHFGCPC.DMD<IntroCutscene+OIBLPHFGCPC::MoveNext>(IntroCutscene/OIBLPHFGCPC)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.(il2cpp -> managed) MoveNext(intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)

**Comment by Woodi-dev** [comment]
I will release a new version today. Pls, tell me if it helps Does it also happen when you are the lobby leader?
Most of all back screen reports are due to someone didn't load the mod properly

**Comment by Woodi-dev** [comment]
@autumn1438 pls check out v1.21
