### ISSUE TITLE
Leaked mods

### ISSUE THREAD

**Issue by MatuxGG** [Woodi-dev/Among-Us-Sheriff-Mod#111]
Hello,

This is probably not the right place to tell you this but that's the only way I found to contact you. 

I'm Mod Manager's creator, if you know it. This post is only to tell you that there are some leaked mods from you on github (Mario Kart, Nuke) and people told me to provide them in Mod Manager.

From now, I refused to add them with the goal of not making them seen by more people. Do you have any plan for this ? As well, can I add them to Mod Manager ?

If you wanna contact me directly on discord, here is my discord id : Matux#0032

Best regards,

**Comment by Woodi-dev** [comment]
Thank you for telling me. I know. Some members leaked my and other exclusive mods without permission. Sharing and leaking these mods is prohibited. I cannot allow you to add the mods to your Mod Manager. However, feel free to add my public ones.

**Comment by MatuxGG** [comment]
For sure, that's what I was thinking. No worries, I will not include these leaks.

Thanks for allowing me to use your public ones tho :)
