### ISSUE TITLE
the mod is not loading its just opens the normal game

### ISSUE THREAD

**Issue by dxzorro** [Woodi-dev/Among-Us-Sheriff-Mod#118]

**Comment by Woodi-dev** [comment]
Make sure you followed all install step.
You might be missing some c++ libs. Please install [https://aka.ms/vs/16/release/vc_redist.x86.exe](https://aka.ms/vs/16/release/vc_redist.x86.exe)

**Comment by demeki** [comment]
Hi! When I tried to donwload redist.x86 it still doesn't work. Also I tried to download redist.x64, but it still running the normal game. I followed all install steps. I tried to delete and extract the files again and again and to restart my PC. Unfortunetly, it's still running the normal game. I wonder, is there any missing files that I need to download too? Or any other solutions? Please help! :(

**Comment by Woodi-dev** [comment]
Allright then pls give me full infromation.
Is it steam version?
What among us version?
What OS do you have?
Can you play other bepinex based mods?
Also please paste the logoutput.txt file here if it exists

**Comment by demeki** [comment]
Hi mate! My steam is updated on the last version, but if you want to know
exactly which version it is, I don't know how to check it out. My Among Us
version is v2021.3.5s(latest one I think). I have Windows 10 home. This is
my first mode based on bepinex, which I am trying to play, so not sure
actually I can play others. And here is the logoutput.txt file:
 [UnityDoorstop]
# Specifies whether assembly executing is enabled
enabled=true
# Specifies the path (absolute, or relative to the game's exe) to the
DLL/EXE that should be executed by Doorstop
targetAssembly=BepInEx\core\BepInEx.IL2CPP.dll
# Specifies whether Unity's output log should be redirected to <current
folder>\output_log.txt
redirectOutputLog=false

[MonoBackend]
runtimeLib=mono\MonoBleedingEdge\EmbedRuntime\mono-2.0-sgen.dll
configDir=mono\MonoBleedingEdge\etc
corlibDir=mono\Managed

I think you need this, right?

**Comment by Woodi-dev** [comment]
This is not the content of the logoutput.txt file. It is the doorstop_config file.
Please paste the content of LogOutput.txt located in the bepinex folder (if exists)

**Comment by demeki** [comment]
Hey, sorry for late reply. Nah... there is nothing like LogOutput.txt in bepinex folder. Should I have it? And I think I don't have a preloader file in the root directory. Idk actually what is that and how it looks like.  How does it look like?
