### ISSUE TITLE
Sheriff Mod installation failure

### ISSUE THREAD

**Issue by Riggsel** [Woodi-dev/Among-Us-Sheriff-Mod#121]
Hey there, 
first, thanks for your contribution and your work, much appreciated. 
I just tried to install your sheriff mod for my daughter, but the mod hint isn't seen in the top left corner when starting from the modified steam folder.
My steps for installation:
1. I downloaded your zip file
2. I made a copy of /Steam/steamapps/common/Among Us/ to /Steam/steamapps/common/Among Us Sheriff/
3. I copied the files from the zip file to the Among Us Sheriff/ directory.
4. I started the Among Us.exe from the  Among Us Sheriff/ directory.

**Result**: No updated version text on the top left corner.

I figured that there was an updated entry in one of the preloader.log files which says:

System.IO.DirectoryNotFoundException: Could not find a part of the path "C:\Program Files (x86)\Steam\steamapps\common\Among Us Sheriff\BepInEx\unhollowed\temp\DummyDll\Il2CppDummyDll.dll".
I already followed your suggestion and installed:
"You might be missing some cpp libs (software libraries used by the mod); please install visual studio c++"
But still, it doesn't seem to work for me. I still get the normal version shown top left. 
I restarted both, steam and pc, but nothing. 

I hope you can help there, thanks in advance.

Kind regards

**Comment by Woodi-dev** [comment]
What OS do you have?
Try to remove the unhollowed folder located in bepinex and start again.
