### ISSUE TITLE
update

### ISSUE THREAD

**Issue by tartsharpcobra** [Woodi-dev/Among-Us-Sheriff-Mod#123]
the airship JUST released!

**Comment by Woodi-dev** [comment]
jup, sheriff mod will be updated within the next hour!

**Comment by Woodi-dev** [comment]
nvm they updated it again .. *TRIGGERED*

**Comment by tartsharpcobra** [comment]
OH NO

**Comment by ImPROster** [comment]
Oh please hurry up!

**Comment by Light-Oxygen** [comment]
Will the new version of Sheriff gonna be respectful with the new Code of Conduct?

**Comment by Woodi-dev** [comment]
@Light-Oxygen what do you mean with Code of Conduct exactly?

**Comment by Light-Oxygen** [comment]
@Woodi-dev According to the last information from Among Us, a new regulation for the game has been published against cheats and game hacks. As mods are injected in the executable file using BepInEx, my question is about the anti-cheat (which may be upgraded), do you think that it could detect the new version of the mod as a cheat and ban from the game?

**Comment by studentism** [comment]
@ImPROster
> Oh please hurry up!

jfc, man. dude's doing a lot of work here for free, foh with that attitude.

@Light-Oxygen please don't take this as gospel, but i haven't detected any sort of anti-cheat before or after this update. the new update has made it more difficult to package using wine, though; as if they're actually trying to implement DRM.

**Comment by Woodi-dev** [comment]
@Light-Oxygen indeed many players are worried about the new report system. However, I am in contact with the devs and they told me they allow Custom RPC calls and mods on their servers. So there is no detection system like VAC implemented. The new report system is based on tickets. If one uses a mod (i speak for all) to gain advantages then the modder is just a cheater in my opinion and deserves to get banned. If players responsibly use mods the devs won't take action against modders.

**Comment by Light-Oxygen** [comment]
@Woodi-dev Oh, okay, thanks !

**Comment by Light-Oxygen** [comment]
@studentism I've not seen you mention sorry, but I'm agree with you ^^

**Comment by Woodi-dev** [comment]
I have updated the mod to the newest version. However, due to the number of bugs Among Us has now a new version will come soon
