### ISSUE TITLE
v2021.3.31.3s Source Code

### ISSUE THREAD

**Issue by georgejeno8** [Woodi-dev/Among-Us-Sheriff-Mod#127]
Hi Woodi,

Would it be possible for the v2021.3.31.3s release plugin source code to be pushed to the repository?  I learned a lot by looking at the source from previous releases, and am really interested in trying to test out a custom mod using your code as a starting point with the new game update.

Thanks for all the work you've put in!

**Comment by Woodi-dev** [comment]
Sure I will upload it. I would recommend the  modding API Reactor to learn creating mods

**Comment by georgejeno8** [comment]
Thanks!

**Comment by Woodi-dev** [comment]
done
