### ISSUE TITLE
among us sherrif wont work

### ISSUE THREAD

**Issue by SlitheryBoy151** [Woodi-dev/Among-Us-Sheriff-Mod#128]
![image](https://user-images.githubusercontent.com/82454353/114557549-b1949e80-9c61-11eb-8fb4-b0bc818c9def.png)

**Comment by Woodi-dev** [comment]
I think you have an older Among Us version.
Make sure you download the latest Among Us Steam version and install the correct Sheriff Mod version.
Normally UnityPlayer.dll is located in your game´s folder

**Comment by SlitheryBoy151** [comment]
ye it works sorry for that
