### ISSUE TITLE
Among us mods not working :(

### ISSUE THREAD

**Issue by Nikeeey** [Woodi-dev/Among-Us-Sheriff-Mod#132]
After i copy paste the contents in the zip folder to the among us local files, only the normal among us is showing up. I tried it with various mods and even reinstalled the game but nothing worked. Please help ( I use steam version)

**Comment by Woodi-dev** [comment]
Make sure you downloaded the right version.
Also try to install the c++ libs: https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by Nikeeey** [comment]
I play with my friends with my friends and I use the mod version they send me. It works for them but not for me. What should i do after installing and set up the c++ libs?

**Comment by Woodi-dev** [comment]
just install the exe and open the game again

**Comment by Nikeeey** [comment]
It is working now. Thank you so much for helping and for taking the time. Means a lot :))))

**Comment by Woodi-dev** [comment]
no problem man. Have fun!
