### ISSUE TITLE
I dont see loaded sheriff mod by woodi at the top

### ISSUE THREAD

**Issue by Tovarisch642** [Woodi-dev/Among-Us-Sheriff-Mod#14]
I extracted the files from the zip and copied them all into the among us folder and I dont see loaded sheriff mod by woodi at the top and the mod is not working

**Comment by Woodi-dev** [comment]
Which Operating System do you have? Make sure u start the game via Among Us.exe in the folder. Do not start via steam

**Comment by Tovarisch642** [comment]
windows 10 home edition x64 bit among us is a cracked version

**Comment by Tovarisch642** [comment]
![Capture](https://user-images.githubusercontent.com/76786202/103440834-8f968380-4c51-11eb-96a3-b9dfe5a3b41f.PNG)

**Comment by Woodi-dev** [comment]
Currently i am not developing this mod for the cracked version of the game. (I wanna support Innersloth).

**Comment by Woodi-dev** [comment]
There might be some compatibility problems with Windows 7/8.

**Comment by par5ul1** [comment]
I have already sent you something about this on Reddit but it may not hurt to post it in the official issues here too:

I'm running Windows 10 on a virtual machine (Parallels) on Mac. Perhaps I don't have the needed dependencies. Any chance you could say what they are so I manually install them?

**Comment by CStafford-14** [comment]
I'm running this on Ubuntu 20.04, which I know shouldn't work, but this appears to already be an issue so...
I should have the same solution you give to par5ul1 as it could be a dependency issue.

I do have the steam version (I start it with the .exe though), so it's not cracked (whatever that is, Among Us doesn't have any DRM so I'm not sure if it can be "cracked")

**Comment by aMinyGameCreator** [comment]
I have the steam vertion but after the first launch it didnt worked anymore. what to do?

**Comment by DeadskiTrevski** [comment]
My friend is also unable to run the sheriff mod while running windows 10 on her Mac. Might be missing a dependency or something. Does anyone have a fix for this?

**Comment by Kelbie** [comment]
So I am running windows 10 on a MacBook and it works fine however my friend who also has a MacBook and is running windows 10 is having trouble installing it. I ensured every step was done correctly even with a fresh install of the game but it didn't work.

**Comment by GodTamIt** [comment]
I'm having the same issue, and there's no output in the `BepInEx` folder for logs.

I am running this on Windows 10 in VirtualBox -- happy to help debug this.

**Comment by adamsaghy** [comment]
[Message: Preloader] BepInEx 6.0.0.0 - Among Us
[Info   : Preloader] Running under Unity v2019.4.9.5308042
[Debug  : Preloader] Game executable path: E:\Steam\steamapps\common\Among Us\Among Us.exe
[Debug  : Preloader] Unhollowed assembly directory: E:\Steam\steamapps\common\Among Us\BepInEx\unhollowed
[Debug  : Preloader] BepInEx root path: E:\Steam\steamapps\common\Among Us\BepInEx
[Message:   BepInEx] Chainloader initialized
[Debug  : Preloader] Runtime invoke pointer: 0x78826B70
[Debug  : Preloader] Runtime invoke patched
[Debug  :   BepInEx] Examining 'E:\Steam\steamapps\common\Among Us\BepInEx\plugins\SherifMod.dll'
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [Sheriff Mod 1.0.1.0] - E:\Steam\steamapps\common\Among Us\BepInEx\plugins\SherifMod.dll
[Message:Sheriff Mod] Sheriff Mod loaded
[Message:   BepInEx] Chainloader startup complete
[Debug  : Preloader] Runtime invoke unpatched
[Error  :    Detour] System.NullReferenceException: Object reference not set to an instance of an object
  at SheriffMod.PlayerControlPatch.Postfix (KMOGFLPJLLK IOFBPLNIJIC) [0x0000b] in <caefeba342a44f608256d384b708505e>:0 
  at (wrapper dynamic-method) FFGALNAPKCD.DMD<FFGALNAPKCD::RpcSyncSettings>(FFGALNAPKCD,KMOGFLPJLLK)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<(il2cpp -> managed) RpcSyncSettings>?93846242::(il2cpp -> managed) RpcSyncSettings>(intptr,intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)
[Error  :    Detour] System.NullReferenceException: Object reference not set to an instance of an object
  at SheriffMod.HudPatch.Postfix (PIEFJFEOGOL __instance) [0x00034] in <caefeba342a44f608256d384b708505e>:0 
  at (wrapper dynamic-method) PIEFJFEOGOL.DMD<PIEFJFEOGOL::Update>(PIEFJFEOGOL)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<(il2cpp -> managed) Update>?44255907::(il2cpp -> managed) Update>(intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)

**Comment by Woodi-dev** [comment]
#52
