### ISSUE TITLE
New roles support?

### ISSUE THREAD

**Issue by unit-a-user** [Woodi-dev/Among-Us-Sheriff-Mod#140]
I suggest to add support for new versions of Among Us, with 4 new roles. 
- Scientist can't be killed by sheriff.
- Engineer can't be killed by sheriff (mistake will cause sheriff to dead).
- Guardian Angel can't be killed by sheriff.
- Shapeshifter can be killed by sheriff in any form, he is defenseless, and no shapeshift will help him. 
- However, the sheriff can mistake the shapeshifter for anyone and die. 
- Sheriff may think that vented imposter, and confuse with engineer, and die. 
- Nobody not know who is sheriff

**Comment by Woodi-dev** [comment]
These are really good ideas. To be honest, I thought they gonna add the sheriff role, so I have to stop this project. 
But let me see what i can do ;)

**Comment by Fulbion** [comment]
Hi! The mod is still usable?

**Comment by ItstheJake** [comment]
We will try our best to work on that
Thank you for suggesting to our Among-Us-Sherrif-Mod
