### ISSUE TITLE
Issue with languages

### ISSUE THREAD

**Issue by TheSpringBoy** [Woodi-dev/Among-Us-Sheriff-Mod#23]
Hi,
when the game is in a path with non english latters, the custom settings (show sheriff) is not showing and you cant change it.

**Comment by CrabHead** [comment]
um what
elaborate

**Comment by Woodi-dev** [comment]
Can you give me example? I got it working with arabic letters

**Comment by TheSpringBoy** [comment]
I used it with my native language - Hebrew.
download this zip and see what I ment. the option for show shriff is just missing.
https://drive.google.com/open?id=1_tsWdloIlR3fP-fUL3KbPL2EEaJ36uGx
