### ISSUE TITLE
Issue when impostor

### ISSUE THREAD

**Issue by TheSpringBoy** [Woodi-dev/Among-Us-Sheriff-Mod#24]
when you are Impostor, you don't see the red line around the crewmates you want to kill

**Comment by Woodi-dev** [comment]
Thanks for your report. What did you do exactly before? Unfortunately I cannot reproduce this bug.

**Comment by TheSpringBoy** [comment]
Just extract the files...
It's the same for my friends

**Comment by TheSpringBoy** [comment]
now I can actually see it in youtube videos. so its clearly problem with the mod..
When you are the impostor, you can see a red line around who you want to kill, but with the mod, when you are impostor you do not see it.

**Comment by Woodi-dev** [comment]
can you send me a clip of the specific youtube video?. This would help me.

**Comment by TheSpringBoy** [comment]
sorry I didnt reply.
the video - https://youtu.be/7e0Xw9VqidY?t=186
as you can see, there is no red line on the nearest character.
if you didnt understand, here some images:

**with the mode:**
![image](https://user-images.githubusercontent.com/75606783/104096233-ef210e80-52a3-11eb-8ad8-28866309b41e.png)**

**without the mode:**
![image](https://user-images.githubusercontent.com/75606783/104096250-0829bf80-52a4-11eb-9f04-86fecf738a09.png)
