### ISSUE TITLE
source and docs

### ISSUE THREAD

**Issue by coolkingcole** [Woodi-dev/Among-Us-Sheriff-Mod#25]
I appreciate the work you have done, this is a really fun mod, but I was wondering if you will be posting how the mod works and general docs so it can be collaborated on. Also while the zipped packages are very nice, it is a little strange to only have the zip on the repo and not the source.

**Comment by Tobiti** [comment]
He just closed my issue with the same question. So I think I will recreate this plugin and release the code on github.

**Comment by coolkingcole** [comment]
> He just closed my issue with the same question. So I think I will recreate this plugin and release the code on github.

Lmk the repo you make, I can try to help.

**Comment by NateKomodo** [comment]
yeah having the mod on github but not committing the code to github is dumb

**Comment by NateKomodo** [comment]
I decompiled it, its a BepInEx plugin, here is the source code for just the plugin: https://anonfiles.com/ZdF2787dp6/SherrifMod_zip

You can find the dependencies and everything required to run it in the zip file from the latest release on this repo

**Comment by Woodi-dev** [comment]
There is an WIP modding lib called reactor.gg. Check it out.

**Comment by Tobiti** [comment]
@Woodi-dev Am I allowed to release the source with my current changes? I added the possibility to modify the sheriff count and the sheriff kill cooldown

**Comment by NateKomodo** [comment]
> @Woodi-dev Am I allowed to release the source with my current changes? I added the possibility to modify the sheriff count and the sheriff kill cooldown

https://github.com/Woodi-dev/Among-Us-Sheriff-Mod/blob/main/LICENSE

**Comment by Tobiti** [comment]
Does someone know how I can increase the scroll canvas in the game options? Because some options are not showing up

**Comment by Woodi-dev** [comment]
> > @Woodi-dev Am I allowed to release the source with my current changes? I added the possibility to modify the sheriff count and the sheriff kill cooldown
> 
> https://github.com/Woodi-dev/Among-Us-Sheriff-Mod/blob/main/LICENSE

Yes you can, but I will appreciate if you link to the original project. I will release a new version where you set the sheriff cooldown too.

**Comment by Tobiti** [comment]
I created a fork and uploaded the source ^^

**Comment by Tobiti** [comment]
I alltough added the ability to change the sheriff count and cooldown

**Comment by Woodi-dev** [comment]
good job!

**Comment by Tobiti** [comment]
> > He just closed my issue with the same question. So I think I will recreate this plugin and release the code on github.
> 
> Lmk the repo you make, I can try to help.

Just go to my fork ^^

**Comment by hennedo** [comment]
His license includes a condition to publish the soucecode, yet no code to see here ....

**Comment by Tobiti** [comment]
> His license includes a condition to publish the soucecode, yet no code to see here ....
> 
> EDIT: he also violates the license of bepinex which he uses, so there is a possibility of a lawsuit ;)

No he isnt, because bepinx license only is for modifications of bepinex and not for plugins for it

**Comment by Woodi-dev** [comment]
@hennedo check out @Tobiti forks. There you find the source. I do not want to discuss this anymore
