### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by AMNDOaksndoAN** [Woodi-dev/Among-Us-Sheriff-Mod#26]
After the "Shhh" or role reveal, My screen is just black, but I can hear sounds.

**Comment by Woodi-dev** [comment]
Make sure everybody in the lobby has the mod. If this bug still exists, please paste the content of bepinex/LogOutput.txt

**Comment by AMNDOaksndoAN** [comment]
Everybody has the mod and sure.
https://anonfiles.com/X9Y0ub78p7/LogOutput_log

**Comment by Woodi-dev** [comment]
aarrghhh its not the official steam version.. Among.Us.v2020.12.9s.Incl.Pets
