### ISSUE TITLE
.zip download flagged as virus

### ISSUE THREAD

**Issue by KingsMMA** [Woodi-dev/Among-Us-Sheriff-Mod#32]
The .zip file is flagged as a virus - https://www.virustotal.com/gui/file/a120155d976ab06f032fb13814f317e98b339d74da47c142f26421ae2a348c2b/detection

**Comment by Woodi-dev** [comment]
I can guarantee you 100% this is not a virus. Someone here in the Issues thread decompiled my code and released the source code. You can check it out to be safe. It is a bepinex plugin that loads its content vis winhttp.dll. It may be that Zillya detects this dll as a suspicious program.
However, as you can see all other Virus checkers confirmed that it is not a virus!

**Comment by KingsMMA** [comment]
How do you re-compile the source code?
