### ISSUE TITLE
Unstable when running on Linux with Steam Proton/WINE

### ISSUE THREAD

**Issue by ItsRogueRen** [Woodi-dev/Among-Us-Sheriff-Mod#40]
I'm trying to make this work in Wine or Proton so I won't need to reboot for just one game, however the mod makes the game EXTREMELY unstable and it can crash at literally any moment. I made a lobby and it crashed. I made another lobby, and then it didn't crash until I went to the laptop. I launched the game a 3rd time, it crashed on the title screen. I can't find a consistent place where it crashes and it seems random.

I'm running the game with Proton-5.21-GE which for the vanilla game runs like its Linux native. Its only the mod that makes it this way. Running with standard Wine is even worse as while it doesn't crash, making a lobby makes the game completely black and you can't see anything (you can hear menu sounds so it seems like it never even leaves the menu to make a lobby, it just blacks out the game screen).

OS: Pop!_OS 20.10 (Ubuntu based)
GPU: Nvidia GTX 970
CPU: Intel i5-4690K @ 3.9GHz
RAM: 16GB DDR3

EDIT: spelling

**Comment by Woodi-dev** [comment]
Seems like a backend problem(bepinex). You could paste the content of logoutput.txt located in bepinex. It may help

**Comment by ItsRogueRen** [comment]
Output from it crashing on the title menu

[Message: Preloader] BepInEx 6.0.0.0 - Among Us
[Info   : Preloader] Running under Unity v2019.4.9.5308042
[Debug  : Preloader] Game executable path: E:\Steam\steamapps\common\Among Us\Among Us.exe
[Debug  : Preloader] Unhollowed assembly directory: E:\Steam\steamapps\common\Among Us\BepInEx\unhollowed
[Debug  : Preloader] BepInEx root path: E:\Steam\steamapps\common\Among Us\BepInEx
[Message:   BepInEx] Chainloader initialized
[Debug  : Preloader] Runtime invoke pointer: 0x78826B70
[Debug  : Preloader] Runtime invoke patched
[Debug  :   BepInEx] Examining 'E:\Steam\steamapps\common\Among Us\BepInEx\plugins\SherifMod.dll'
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [Sheriff Mod 1.0.1.0] - E:\Steam\steamapps\common\Among Us\BepInEx\plugins\SherifMod.dll
[Message:Sheriff Mod] Sheriff Mod loaded
[Message:   BepInEx] Chainloader startup complete
[Debug  : Preloader] Runtime invoke unpatched
[Error  :    Detour] System.NullReferenceException: Object reference not set to an instance of an object
  at SheriffMod.PlayerControlPatch.Postfix (KMOGFLPJLLK IOFBPLNIJIC) [0x0000b] in <caefeba342a44f608256d384b708505e>:0 
  at (wrapper dynamic-method) FFGALNAPKCD.DMD<FFGALNAPKCD::RpcSyncSettings>(FFGALNAPKCD,KMOGFLPJLLK)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<(il2cpp -> managed) RpcSyncSettings>?93846242::(il2cpp -> managed) RpcSyncSettings>(intptr,intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)
[Error  :    Detour] System.NullReferenceException: Object reference not set to an instance of an object
  at SheriffMod.HudPatch.Postfix (PIEFJFEOGOL __instance) [0x00034] in <caefeba342a44f608256d384b708505e>:0 
  at (wrapper dynamic-method) PIEFJFEOGOL.DMD<PIEFJFEOGOL::Update>(PIEFJFEOGOL)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.DMD<DMD<(il2cpp -> managed) Update>?44255907::(il2cpp -> managed) Update>(intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)

**Comment by ItsRogueRen** [comment]
After the crash I made a lobby, but Sheriff options were not there

**Comment by Woodi-dev** [comment]
did you see Sheriff Mod loaded in the menu?

**Comment by ItsRogueRen** [comment]
It crashed too quickly to tell

**Comment by ItsRogueRen** [comment]
> did you see Sheriff Mod loaded in the menu?

Upon removing and reinstalling the mod, it does NOT show Sheriff Mod Loaded

**Comment by Woodi-dev** [comment]
i guess so... i got several compatibility issues regarding bootcamp, a VM or WINE.

**Comment by ItsRogueRen** [comment]
WINE would be the best solution to running this on non-Windows Operating Systems as it works on MacOS Linux BSD etc. (although Apple doesn't give a rat's a** about being able to run games by removing all 32-bit support and not adding Vulkan)

**Comment by Woodi-dev** [comment]
Can you change the dll override for winhttp.dll to "Native then Builtin" in your wine.cfg? This could help...

**Comment by ItsRogueRen** [comment]
I'm not sure how to do that for Proton. Running Among Us in standard Wine results in no sound so I replace the files in the steam folder for the game so it can run with Proton

**Comment by mxbl1337** [comment]
Changing the dll override for winhttp.dll to "Native then Builtin" does the trick. Also what i did was i installed Among Us in a windows vm with the mod, then copied over the game files and installed dxvk so sound would work properly with wine.

**Comment by ItsRogueRen** [comment]
> Changing the dll override for winhttp.dll to "Native then Builtin" does the trick. Also what i did was i installed Among Us in a windows vm with the mod, then copied over the game files and installed dxvk so sound would work properly with wine.

How do I do this? Opening in a text editor just shows a garbbed up mess of symbols

**Comment by ItsRogueRen** [comment]
Mod does load, but I

> Changing the dll override for winhttp.dll to "Native then Builtin" does the trick. Also what i did was i installed Among Us in a windows vm with the mod, then copied over the game files and installed dxvk so sound would work properly with wine.

Mod does load, but I cannot join/start a lobby without being stuck on a black screen: https://i.imgur.com/kQSEEYG.png
