### ISSUE TITLE
Add "Q" for kill shortcut for sheriff kill

### ISSUE THREAD

**Issue by GuruPrasaathM** [Woodi-dev/Among-Us-Sheriff-Mod#44]
Hey there! I know this feels rather insignificant, But for PC users, The game feels really unbalanced as a sheriff without a keyboard shortcut to kill, As the imposters seem to quickly sense the danger and kill the sheriff before the sheriff is able to manually hover the mouse to kill them, I am not sure if its possible to add a shortcut, But will certainly be a improving and helpful upgrade if possible.

**Comment by Woodi-dev** [comment]
Yeah its alrdy done. I will upload a new version this week
