### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Jazper06** [Woodi-dev/Among-Us-Sheriff-Mod#46]
Close this it works

**Comment by Jazper06** [comment]
So i open the game in steam/steamapps/common/among us sheriff, it loads, then it crashes and loads again. Then i come in the homescreen, but the mod isn't there.

**Comment by Woodi-dev** [comment]
> Close this it works

Does it work?

**Comment by Jazper06** [comment]
> > Close this it works
> 
> Does it work?

Yes
