### ISSUE TITLE
Not Working.

### ISSUE THREAD

**Issue by ShaunakPemmaraju** [Woodi-dev/Among-Us-Sheriff-Mod#48]
I have extracted into the folder but when i open the game it loads the normal game.

**Comment by Woodi-dev** [comment]
What Windows do you have? Is it 7/8/10 and is it home or pro?

**Comment by barmycarmy** [comment]
Hi there. Sorry to jump on the post but I'm having exactly the same issue. I'm running Windows 10 Pro. Have done everything but when i open it does what @ShaunakPemmaraju says and loads the normal game.

**Comment by ShaunakPemmaraju** [comment]
> What Windows do you have? Is it 7/8/10 and is it home or pro?

Umm... Its a Windows 10 Home - HP Pavillion 15

**Comment by Woodi-dev** [comment]
can you add this: redirectOutputLog=true
in the last line of doorstop_config.ini

so your config looks like:
[MonoBackend]
runtimeLib=mono\MonoBleedingEdge\EmbedRuntime\mono-2.0-sgen.dll
configDir=mono\MonoBleedingEdge\etc
corlibDir=mono\Managed

[UnityDoorstop]
enabled=true
targetAssembly=BepInEx\core\BepInEx.IL2CPP.dll
redirectOutputLog=true

run it and paste the content of output_log.txt

**Comment by barmycarmy** [comment]
Sorry to jump on this post but im having the same issue too. Did what you said regarding the redirectOutputLog=true

Heres my outputlog
Initialize engine version: 2019.4.9f1 (50fe8a171dd9)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Among Us - Copy/Among Us_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Intel(R) UHD Graphics 630 (ID=0x9bc8)
    Vendor:   (null)
    VRAM:     3967 MB
    Driver:   27.20.100.8681
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 8.705500 ms
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
LHNDJOJKPOO:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Loaded server: Europe-Master-1: 172.105.251.170:22023
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AOBNFCIHAJL:BBIDOJKFGPM()
AOBNFCIHAJL:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Resumed Game
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
KHNHJFFECBP:OnApplicationPause(Boolean)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

C:\Program Files (x86)\Steam\steamapps\common\Among Us - Copy\Among Us_Data\Resources\AmongUsHelper.exe
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Twitch.TwitchManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Uploading Crash Report
InvalidOperationException: Steamworks is not initialized.
  at Steamworks.InteropHelp.TestIfAvailableClient () [0x00000] in <00000000000000000000000000000000>:0 
  at OCHALHNBMII.Start () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Requesting announcement from: 172.105.251.170
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
CBIIBJDBFAJ:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Loading secure: C:/Users/barmy/AppData/LocalLow/Innersloth/Among Us\secureNew
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
HAPPPIPACLG:EDLKGGJPKEB(Action`1)
IANFCOGHJMJ:FANNOEKHEJE()
IANFCOGHJMJ:EAOHLADJCMA(String)
DBMNHPJMECE:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 2fb4 -> priority: 1 
  Thread -> id: 18d4 -> priority: 1

**Comment by Woodi-dev** [comment]
please try to install 
https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by ShaunakPemmaraju** [comment]
I did not understand what you mean by "run it and paste the content of output_log.txt"

**Comment by ShaunakPemmaraju** [comment]
Ok I'm sending the output-
[output_log.txt](https://github.com/Woodi-dev/Among-Us-Sheriff-Mod/files/5828570/output_log.txt)

**Comment by ShaunakPemmaraju** [comment]
"Currently i am not developing this mod for the cracked version of the game. (I wanna support Innersloth)."

Well I got it from this site - blob:https://mega.nz/5f15c0bf-9197-4b22-bbb1-bce9f8f3e4ee

**Comment by ShaunakPemmaraju** [comment]
@Woodi-dev could you add the among us.exe file with all modifications and then send it? Just saying cuz it would be much easier.

**Comment by Woodi-dev** [comment]
@ShaunakPemmaraju I am not allowed to share the game due copyright

**Comment by ShaunakPemmaraju** [comment]
Ok. What is the problem with the mod not loading? This is my folder-
![image](https://user-images.githubusercontent.com/73421617/104916796-8bd86000-59b8-11eb-9f39-2830972cdb76.png)

**Comment by Woodi-dev** [comment]
the installation looks good. Did you try to install https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by ShaunakPemmaraju** [comment]
No, I have Family Safety on my PC, it doesnt allow to use setup exe files.

**Comment by Woodi-dev** [comment]
However, i guess you are missing some runtime libs. https://aka.ms/vs/16/release/vc_redist.x86.exe worked for a lot of people.
I cannot help you if you are not allowed to install it

**Comment by ShaunakPemmaraju** [comment]
Is there any way with which I can update?

**Comment by mudassirzulfiqar** [comment]
https://github.com/Woodi-dev/Among-Us-Sheriff-Mod/issues/48#issuecomment-762914381
This solved my issue Thanks

**Comment by LeoMouyna** [comment]
@Woodi-dev It might be a good idea to add this on your install documentation 👌

**Comment by amberbeann** [comment]
Hi, I have this problem too, but I don't understand the fix.. I have installed https://aka.ms/vs/16/release/vc_redist.x86.exe but don't know where to go from there, please let me know if you can help, thanks!

**Comment by mudassirzulfiqar** [comment]
@amberbeann I think you may need to uninstall the among us game via CC cleaner, and re install it.

**Comment by LeoMouyna** [comment]
@amberbeann when I installed visual studio c++, I just l launched AmongUs.exe again and it was all right. Don't you see `loaded Sheriff Mod v1.1 by Woodi ` ?

**Comment by Ayoitsjada** [comment]
can you download it on mobile?Because i really want to play it and i dont have any pc

**Comment by Woodi-dev** [comment]
> can you download it on mobile?Because i really want to play it and i dont have any pc

No sry. This mod uses bepinex as a backend. Unfortunately, It is for Windows only.

**Comment by ShaunakPemmaraju** [comment]
@Woodi-dev I got a C++ compiler from codeblocks.org but idk what to do from here..

**Comment by CoolCat467** [comment]
This mod utilizes the bepinex patcher, which from my knowledge at this time works best on windows and may not be possible to run on other operating systems. Running on android would be very difficult, and would pretty much would need the entire mod to be re-written to use something other than bepinex that would also work on android. C++ compiler doesn't matter. Try to re-install it, and if you can't because of windows permissions, then too bad. Woodi has given you all the resources to be able to do it, and if you can't follow it for some reason quit complaining and deal with it.
