### ISSUE TITLE
It´s loading but when game starts the screen stays black

### ISSUE THREAD

**Issue by SamuelEris** [Woodi-dev/Among-Us-Sheriff-Mod#51]
So i can load the game with the mods and everything however when the host starts the game the screen stays black and i can´t see a thing.

**Comment by Woodi-dev** [comment]
Make sure evsrbody in the lobby has installed the mod. Joining public lobbies does not imply a lobby with players who installed the mod.  Try to create a lobby with 3 friends and try it again. Otherwise paste the content of bepinex/logoutput.txt

**Comment by aelias1234** [comment]
i have this issue when hosting alone. do i need people or is it just me?

**Comment by Danial2k11134** [comment]
I want know how to use sherif mode pls
