### ISSUE TITLE
Mod Among Us.exe loading Normal Game

### ISSUE THREAD

**Issue by barmycarmy** [Woodi-dev/Among-Us-Sheriff-Mod#52]
I seem to be having the same issues as others. Have done a copy of the Among Us folder, extracted the mod into that folder but when i run Among Us within that folder it loads as the normal game. Have tried various ways, friends have tried we just cant seem to get it to load the mod at all. Tried uninstalling and reinstalling but no joy.

I'm running Windows 10 Pro. It is a brand new build, so everything has been installed clean. Unsure it that makes a different or not?

**Comment by Woodi-dev** [comment]
can add this: redirectOutputLog=true
in the last line of doorstop_config.ini

so your config looks like:
[MonoBackend]
runtimeLib=mono\MonoBleedingEdge\EmbedRuntime\mono-2.0-sgen.dll
configDir=mono\MonoBleedingEdge\etc
corlibDir=mono\Managed

[UnityDoorstop]
enabled=true
targetAssembly=BepInEx\core\BepInEx.IL2CPP.dll
redirectOutputLog=true

run it and paste the content of output_log.txt

**Comment by barmycarmy** [comment]
Thanks. Done that, heres the output log.

Initialize engine version: 2019.4.9f1 (50fe8a171dd9)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Among Us - Copy/Among Us_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Intel(R) UHD Graphics 630 (ID=0x9bc8)
    Vendor:   (null)
    VRAM:     3967 MB
    Driver:   27.20.100.8681
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 8.705500 ms
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
LHNDJOJKPOO:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Loaded server: Europe-Master-1: 172.105.251.170:22023
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AOBNFCIHAJL:BBIDOJKFGPM()
AOBNFCIHAJL:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Resumed Game
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
KHNHJFFECBP:OnApplicationPause(Boolean)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

C:\Program Files (x86)\Steam\steamapps\common\Among Us - Copy\Among Us_Data\Resources\AmongUsHelper.exe
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Twitch.TwitchManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Uploading Crash Report
InvalidOperationException: Steamworks is not initialized.
  at Steamworks.InteropHelp.TestIfAvailableClient () [0x00000] in <00000000000000000000000000000000>:0 
  at OCHALHNBMII.Start () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Requesting announcement from: 172.105.251.170
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
CBIIBJDBFAJ:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Loading secure: C:/Users/barmy/AppData/LocalLow/Innersloth/Among Us\secureNew
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
HAPPPIPACLG:EDLKGGJPKEB(Action`1)
IANFCOGHJMJ:FANNOEKHEJE()
IANFCOGHJMJ:EAOHLADJCMA(String)
DBMNHPJMECE:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 2fb4 -> priority: 1 
  Thread -> id: 18d4 -> priority: 1

**Comment by Woodi-dev** [comment]
Can you try to install the Visual c++ x86 runtime?
https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by morgan-adams** [comment]
@Woodi-dev Not sure about OP but this solution worked for me! I was running a brand-new Parallels VM of Windows 10 and this solved my issue. Thanks!

**Comment by Woodi-dev** [comment]
haha nice !

**Comment by barmycarmy** [comment]
@Woodi-dev that worked! Thanks so much
