### ISSUE TITLE
Crewlink issue

### ISSUE THREAD

**Issue by Zosh8818** [Woodi-dev/Among-Us-Sheriff-Mod#53]
Mine works with Crewlink, but for all my friends it's saying "waiting for Among Us" on Crewlink and it's not linked (it works on normal Among Us). We don't understand what's the difference between us.

**Comment by Woodi-dev** [comment]
It is also working for me tho.. i played it with all my friends and it works, What Crewlink version?

**Comment by Zosh8818** [comment]
2.0.1 I'm really confused tbh

**Comment by Woodi-dev** [comment]
Do you have some more information regarding this issue?
It works fine here

**Comment by Zosh8818** [comment]
Hey thanks for your help man, one of my friends looked at what they did and they changed Among Us.exe and Among Us_data for some reason. We changed it back and now it works.

**Comment by Woodi-dev** [comment]
Ok :)

**Comment by Danial2k11134** [comment]
what you doing can you give me link to play among us
