### ISSUE TITLE
Timeout "6 pings with no answer" v1.1

### ISSUE THREAD

**Issue by zcourge** [Woodi-dev/Among-Us-Sheriff-Mod#55]
Playing this mod has been working flawlessly earlier, but today we updated to 1.1 and have consistently getting random players dropped due to server timeout. This doesn't happen in Vanilla Among Us, we are not using any other mods alongside the Sheriff mod either.

[Here's the error](https://i.imgur.com/sZIBe6e.png)

Any chance you could look into this? It's a cool mod!

**Comment by Tobiti** [comment]
This is happening in vanilla among us today too

**Comment by zcourge** [comment]
Alright I must've been mistaken then, my bad!
