### ISSUE TITLE
Kill Button Active while Task as Sheriff

### ISSUE THREAD

**Issue by CaptainKhaid** [Woodi-dev/Among-Us-Sheriff-Mod#58]
If you do the Fuel task during the game, you can try to kill as Sheriff, which is pretty inconvenient, since you kill yourself if there is someone doing task next to you. 

This can be pretty gamebreaking, since you kill yourself unintentionally during the task. 
This also can happen during Voting Screen.

**Comment by Woodi-dev** [comment]
I totally agree. I have added it to my list. Thanks

**Comment by Woodi-dev** [comment]
Fixed in v1.2
