### ISSUE TITLE
Don't give Sherrif to players who don't have mod

### ISSUE THREAD

**Issue by mathu204** [Woodi-dev/Among-Us-Sheriff-Mod#59]
In my group of 10 there are like 2-3 people who dont have the mod so my request is to make it so that when there are people in the lobby without the mod they are excluded from getting Sherrif. or an option to enable which players the sherrif can be cycled between

**Comment by Woodi-dev** [comment]
Sry I can't agree. This mod is not designed in a way to play with players without the mod. These players do not receive the kill command by the sheriff if they do not install the mod

**Comment by mathu204** [comment]
> Sry I can't agree. This mod is not designed in a way to play with players without the mod. These players do not receive the kill command by the sheriff if they do not install the mod

Alright, I did want everyone to have it but they either play on Mac or their tablet hence they couldn’t get it. And when we did play the sherif was able to kill someone who didn’t have the mod who was an imposter. Will you consider making support for other OS’ in the future?
