### ISSUE TITLE
Kills as sheriff not working properly, (sheriff dead for everyone else and, imposter still alive)

### ISSUE THREAD

**Issue by whyme12** [Woodi-dev/Among-Us-Sheriff-Mod#60]
Hi,

In my last game I was sheriff and killed one imposter, but somehow the game got messed up and registered me as dead for everyone else.
In my game, I was alive and the imposter was dead, but for everyone else the imposter was still alive and I was dead.
I was invisible for everbody else, but was not a ghost and could do emergency tasks.

Maybe some syncronization issue, not sure.

**Comment by Woodi-dev** [comment]
So does it happen when you killed an Impostor? That is very weird.... That means your game thought he was a crewmate.
Yes it is indeed a synchronization error by network lag by the game.

**Comment by whyme12** [comment]
Yes he was an Imposter

**Comment by Kriasrub** [comment]
I have a similar issue. If I kill a player as Sheriff, the person does not die no matter whether he was an impostor or not. Funnily enough the player is a ghost on his screen, but for everyone else, he's just alive. Is there a way to fix this? Or is this even some weird problem with some other mods I might have active at the moment? (I'm testing around which mods work together and which don't)

**Comment by Woodi-dev** [comment]
@Kriasrub this mod was one of the first public mods and was made for a standalone modification of the game. I don't know what mods you have installed. But adding mods will lead to a lot of bugs. (RPC Conflicts, Double Patching.......)
