### ISSUE TITLE
Shortcut to Kill as Sheriff Does Not Work (Q Button)

### ISSUE THREAD

**Issue by dredinger** [Woodi-dev/Among-Us-Sheriff-Mod#63]
Q does nothing when Kill button is highlighted.

**Comment by Woodi-dev** [comment]
ok that's weird. It works for me. Do you use v1.1?
What keyboard layout / language do you use?

**Comment by dredinger** [comment]
EN/US

I'll verify version later, but I installed it as of last week Jan 13.

**Comment by Woodi-dev** [comment]
Yes i guess you have version v1.01

**Comment by dredinger** [comment]
Confirmed, I had 1.01, NOT v1.1.
