### ISSUE TITLE
Problem with other mods

### ISSUE THREAD

**Issue by whitegolum** [Woodi-dev/Among-Us-Sheriff-Mod#64]
Can you put a bool verification before the Sheriff role will be assigned to the crewmates ? for Exemple Sheriff + Mayor : They both use BepInEX and they both work using the same Plugin folder , but both special roles always get assigned to the same crewmate all the time . Will you be able to add something that make it reshuffle the assignement of Sheriff mod to another crewmate if the chosen one already got a special role ?

**Comment by Woodi-dev** [comment]
Idk. At the moment I don't prioritize this issue.
