### ISSUE TITLE
Request: Make it so only crew can see who is Sheriff

### ISSUE THREAD

**Issue by Jaydewhisker** [Woodi-dev/Among-Us-Sheriff-Mod#70]
As the title states, it'd be great if only Crewmates could see who the Sheriff is when Show Sheriff is on, as there is never any use for impostors to know who is Sheriff that would help the crewmates. Maybe make it something like the taskbar settings ,where you have three options, Off, Crewmates Only, and On?

Thanks for this mod, great job with it!

**Comment by Woodi-dev** [comment]
I will keep this in mind for future versions.
