### ISSUE TITLE
Mod not working (Epic Games?)

### ISSUE THREAD

**Issue by kingapfelbaum** [Woodi-dev/Among-Us-Sheriff-Mod#75]
When i did all the steps nothing changes when i start Among Us.exe
I bought the game on epic games and saw I have different files than my friends so maybe that's the problem idk.

Thanks for any help!

**Comment by Woodi-dev** [comment]
Oh yeah, that can be the reason.
Does the version match?

**Comment by kingapfelbaum** [comment]
It's v2020.12.9 idk if that makes a difference,
but I don't know how to change the version

**Comment by senor-roboto** [comment]
Hey, I have the same issue and I have downloaded Among Us on the Epic Games Store
So you're telling me I have to buy it again ??

**Comment by Doryann** [comment]
Hello I have the same issue, the problem can be the version. 
In the steam Among Us, the name of the version is 2021.3.5s but in the Epic one it's 2021.3.5e. But the files architecture of the game is different so it's difficult to say where is the problem .. But the version is a possibility.

**Comment by Ayoitsjada** [comment]
STOP SENDING ME EMAILS
