### ISSUE TITLE
Sherrif Vent Kill - Ghost Chat

### ISSUE THREAD

**Issue by NovaTwine** [Woodi-dev/Among-Us-Sheriff-Mod#78]
Im not sure whether this was intentional or not, but the sheriff can kill an impostor while he is sitting in the vent, if the sherriff stands on top of it. I feel like this should not be possible, because even if the sheriff doesnt kill the imp in the vent, he still KNOWS some1 was there.

Also one of my friends had the issue that he was able to read the ghost chat and see the ghosts as alive players walking around the map. We think the reason why he was able to see the the ghost chat is, because the game didnt register those players actually dying, on his screen, he was still able to vote them in meetings, its like they never died. The problem didnt resolve itself even after a restart in the next game.

great mod, keep up the good work! we had tons of fun last night trying it out!

**Comment by Woodi-dev** [comment]
Thank you i agree with the vent. Unfortunately, the net code and the server lags lead to some bugs...
I am working on a more stable net code at the moment
