### ISSUE TITLE
The archive is in either in unknown format or damaged

### ISSUE THREAD

**Issue by SomeWebsiteDesigner** [Woodi-dev/Among-Us-Sheriff-Mod#80]
When I try to open it, or extract it that's what I get. Literally just that.

**Comment by Danial2k11134** [comment]
Can we download happy mode among us hack

**Comment by Woodi-dev** [comment]
I guess it is a problem with your unzipper. Do you use WinRaR/7zip?

**Comment by LeoMouyna** [comment]
@SomeWebsiteDesigner I can't reproduce your issue, I tried on Windows, Linux and MacOS. Can you add some screenshots ?

**Comment by BCornelsen** [comment]
A friend of mine has the same error using chrome. It works by using another browser.

**Comment by Danial2k11134** [comment]
Why you cant solve the problem can you pls resend send back because i want
that role in my samsung note pls just give it the link

**Comment by Danial2k11134** [comment]
No, I can't. My mom and dad is evil >:) so . He block internet :(

**Comment by Woodi-dev** [comment]
@SomeWebsiteDesigner any updates?

**Comment by BCornelsen** [comment]
Maybe it would be helpful as a minor step to provide a hash of the archives to check the integrity after download.

**Comment by Danial2k11134** [comment]
Thanks for the tip!
