### ISSUE TITLE
Suggestion: Option to Make Server Host Always Sheriff

### ISSUE THREAD

**Issue by PieCreeper12** [Woodi-dev/Among-Us-Sheriff-Mod#86]
I learned something interesting about the sheriff mod. If you create a lobby not on the Custom region, there is still a chance that you can be a sheriff if you have the mod installed. However, those who do not have the mod installed cannot be the sheriff. My suggestion is to make an option where the lobby host is always the sheriff. That way, you can play the sheriff mod with people who do not have the mod installed.

**Comment by Woodi-dev** [comment]
The mod is not designed in a way that you can play with players with a non modded game. If you become Sheriff and you kill and non modded player, only you will see how the target (or die) dies.

**Comment by PieCreeper12** [comment]
Well, that's disappointing.

**Comment by Woodi-dev** [comment]
If that would be possible, one could abuse the sheriff mod for cheating...
