### ISSUE TITLE
Custom region not working.

### ISSUE THREAD

**Issue by PieCreeper12** [Woodi-dev/Among-Us-Sheriff-Mod#87]
I cannot create a lobby on the custom region. When I click "confirm", either nothing happens or the screen just turns black and it disconnects me.

**Comment by Woodi-dev** [comment]
You have to configure a custom server first. 
Open BepInEx/config/org.bepinex.plugins.SheriffMod.txt 
and change the IP address to the IP address of a custom Server. Atm, i do not host a specific custom server for this mod.
However, you can easily host your own server with https://github.com/Impostor/Impostor
