### ISSUE TITLE
Sheriff Mod Problem

### ISSUE THREAD

**Issue by KindaSusXD** [Woodi-dev/Among-Us-Sheriff-Mod#88]
So I did copy the Among us folder and pasted the Sheriff files in there but if i start Among Us i dont have the Mod enabled. I only have Among us Application and not Among Us,exe i dont know if that changes anything but yea. I also tryed both versions of it and both dont work pls help

**Comment by KindaSusXD** [comment]
Nevermind going trough outer reports fixed my problem :)

**Comment by Woodi-dev** [comment]
nice :)
