### ISSUE TITLE
Mod merging

### ISSUE THREAD

**Issue by Miniflint** [Woodi-dev/Among-Us-Sheriff-Mod#97]
here is it 
https://imgur.com/a/LTEsoLK

**Comment by Woodi-dev** [comment]
Sheriff mod is not made in a way to be compatible with others. In general, it's really hard to make all mods working together.

**Comment by Danial2k11134** [comment]
If sherif mod not work i want tell you i watch youtube that say if you
download skeld.net you will get any mod are that true

**Comment by Miniflint** [comment]
> Sheriff mod is not made in a way to be compatible with others. In general, it's hard to make all mods working together. You need to patch these...

Hi
Do you where i can change some coding make it compatible ?
The mod works perfectly, only the interface is a little issue

**Comment by Woodi-dev** [comment]
check out: https://github.com/slushiegoose/Town-Of-Us 
other modders alrdy have done that
